version: '3'
services:
  julia:
    image: segrcdbjl
    container_name: segrcdbjl-julia
    volumes:
      - ./:/workspace/SegRCDB.jl
    working_dir: /workspace/SegRCDB.jl
    command: julia --project=/workspace/SegRCDB.jl

  shell:
    image: segrcdbjl
    container_name: segrcdbjl-julia
    volumes:
      - ./:/workspace/SegRCDB.jl
    working_dir: /workspace/SegRCDB.jl
    command: /bin/bash

  web:
    image: segrcdbjl
    container_name: segrcdbjl-packagedocs
    volumes:
      - ./:/workspace/SegRCDB.jl
    working_dir: /workspace/SegRCDB.jl
    ports:
      - "8000:8000"
    command: make web
